server:
  port: 13000
spring:
  cloud:
    nacos:
      discovery:
        service: skill-service
      server-addr: localhost:8848
  datasource:
    data-username: root
    data-password: root
    url: jdbc:mysql://localhost:3306/skill
  redis:
    host: localhost
    port: 6379