server:
  port: 9001
spring:
  cloud:
    nacos:
      discovery:
        service: product-service
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  datasource:
    url: jdbc:mysql://localhost:3306/skill
    username: root
    password: root
  redis:
    host: localhost
    port: 6379